import '@/app/ui/global.css';

import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Duyet's Resume",
  description: "Templated resume generated by React Next.js",
};

const ubuntu = Ubuntu({
  weight: ["300", "400"],
  subsets: ["latin"],
  display: "swap",
  variable: '--font-ubuntu'
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={ubuntu.className}>
      <head>
        <Script
          src="https://kit.fontawesome.com/7ecb1bd439.js"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </head>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
